[package]
name = "hashassin"
version = "0.1.0"
edition = "2024"

[dependencies]
hashassin_core = { path = "../core" }
clap = { version = "4.0", features = ["derive"] }  # command-line argument parsing
tracing = "0.1"
hex = "0.4.3"